### ISSUE TITLE
Support multiple layers in the HFB layered HFB-classes

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#598] opened 2023-10-23 08:23 UTC
In #556 Layered HFB packages have been added. A user can define multiple linestring and per linestring a layer can be specified, However the layer specified for a linestring is applied to all linestrings

```
barrier_gdf = gpd.GeoDataFrame(
  geometry=
    [
      linestring1,
      linestring2
    ],
  data=
    {
      "hydraulic_characteristic": [1e-3, 1e-3,],
      "layer": [1, 2,]
    },
)


hfb = imod.mf6.LayeredHorizontalFlowBarrierHydraulicCharacteristic(barrier_gdf)
```

In the snippet above I would expect that linestring1 is applied to layer 1 and that linestring2 is applied to layer 2. However linestring1 is applied to layers 1 and 2 and the same applies for linestrin2

**Comment by JoerivanEngelen** [comment] 2024-06-20 13:29
I couldn't reproduce this, however, I see that things go wrong when calling ``to_mf6_pkg`` in this (edge?) case, with a horizontal assigned to layer 1 and a vertical line to layer 2.

```python
import geopandas as gpd
import shapely

import imod

barrier_x1 = [-1000.0, 0.0, 1000.0]
barrier_x2 = [0.0, 0.0, 0.0]
barrier_y1 = [10.0, 10.0, 10.0]
barrier_y2 = [-1000.0, 0.0, 1000.0]

linestring1 = shapely.linestrings(barrier_x1, barrier_y1)
linestring2 = shapely.linestrings(barrier_x2, barrier_y2)

barrier_gdf = gpd.GeoDataFrame(
  geometry=
    [
      linestring1,
      linestring2
    ],
  data=
    {
      "hydraulic_characteristic": [1e-3, 1e-3,],
      "layer": [1, 2,]
    },
)

hfb = imod.mf6.LayeredHorizontalFlowBarrierHydraulicCharacteristic(barrier_gdf)

#%% 
import numpy as np
import xarray as xr


def list_to_da(ls):
    layer = np.arange(len(ls))+1
    return xr.DataArray(ls, coords={"layer": layer}, dims=("layer",))

grid = imod.util.empty_3d(250.0, -500.0, 500.0, 250.0, -500.0, 500.0, [1,2])

active = xr.full_like(grid, 1)
top = list_to_da([10.0, 0.0]) * active
bottom = list_to_da([0.0, -20.0]) * active
k = list_to_da([10.0, 20.0]) * active

hfb.to_mf6_pkg(active, top, bottom, k)

```

In a debugging session, calling ``snapped_dataset["layer"].ugrid.plot()`` results in this:

![image](https://github.com/Deltares/imod-python/assets/9744750/3fe5681d-d1f6-47f3-9fe1-80260f44bb8a)

For some reason the vertical line becomes layer 1 halfway. 

I think the issue stems from the fact that we now snap_to_edges for all layers in one call. I think we should call snap_to_edges for each layer seperately, this would avoid all kinds of unexpected behavior.

**Comment by JoerivanEngelen** [comment] 2024-06-27 14:27
I just had a chat with @HendrikKok, he mentioned the LayeredHorizontalFlowBarrier were never intended to have multiple layers. I'm adding a validation check and updating the docstring.

**Closed** 2024-06-28 14:30 UTC
Labels: story
