### ISSUE TITLE
Remove setup.cfg

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#706] opened 2023-12-21 10:51 UTC
The setup.cfg file is an artefact of the setuptools module. Nowadays all the information stored inside the setup.cfg can also be stored in the pyproject.toml. This has the advantage that all the project information is stored in 1 location

**Comment by JoerivanEngelen** [comment] 2023-12-21 10:55
Duplicate of https://github.com/Deltares/imod-python/issues/560

**Closed by JoerivanEngelen** 2023-12-21 10:55 UTC
