### ISSUE TITLE
Attribute error while importing on google colab 

### ISSUE THREAD

**Issue by Aashi779** [Deltares/imod-python#860] opened 2024-02-21 14:49 UTC
AttributeError: partially initialized module 'imod' has no attribute 'mf6' (most likely due to a circular import)

This is the error while doing import imod after using pip install command in google colab, it is because there is an inbuilt file named imod that is clashing with import command causing circular import error

**Comment by Huite** [comment] 2024-02-21 14:53
Hi @Aashi779 

> it is because there is an inbuilt file named imod

Where does this file come from? If you know this is the case, can't you just rename it and avoid the name collision?

**Comment by Aashi779** [comment] 2024-02-21 15:03
Yes that is the problem, I checked on the internet to resolve this issue, it suggested the same but I could not find the file to work around it.

**Comment by Huite** [comment] 2024-02-21 15:18
You can check the origin of modules:

```python
Python 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:12:32) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import imod
>>> print(imod)
<module 'imod' from 'C:\\src\\imod-python\\imod\\__init__.py'>
```
(I have a local editable install in this case.) 

Maybe this tells you a little more. Otherwise, try pip uninstall and pip install again explicitly.
Regardless, this doesn't seem to be a problem with the `imod` package, it's a problem with installing packages (via pip) on Colab -- I doubt we can be of much help.

If you were working on your own machine, we'd recommend using mamba (or [pixi](https://pixi.sh/)) is recommend to install these scientific computing packages, since installing from conda-forge works a lot smoother than installing from pypi (since it will cross-check dependencies).

**Comment by Aashi779** [comment] 2024-02-21 15:38
Sure, I'll do as suggested. Thanks a lot for helping me out!

**Comment by JoerivanEngelen** [comment] 2024-02-21 16:36
Hi @Aashi779 ,

Thanks for posting this issue. I've reproduced the issue on Google Colab, and I also ran into [this issue](https://github.com/Deltares/imod-python/issues/861).

Apparently we included features in our type annotation in the 0.15.2 release which are unsupported by Python 3.10.
If you install on Python 3.11, things should work accordingly.

**Context:**
- We currently test on Python 3.11, so if possible, this is probably the best python version now to work with iMOD Python
- As Huite mentioned, the preferred way of installing is via mamba, or pixi. This is what most of our users apply so more likely to work.

**Comment by Huite** [comment] 2024-02-21 17:16
Ah, so we could've reproduced it by just installing locally with an older Python version.

@JoerivanEngelen The type annotations can be easily fixed by including `from __future__ import annotations` at the top of the problematic modules. This is what I've been doing for xugrid as well.

**Comment by Aashi779** [comment] 2024-02-21 17:32
Yes @JoerivanEngelen, I tried it with Python 3.11 and it worked well. Thanks a lot for looking into this!

**Comment by JoerivanEngelen** [comment] 2024-02-22 15:43
Investigated this further: I created a pixi environment locally for python 3.10. No errors for circular imports are thrown on my local machine (OS: Windows) with python 3.10, whereas the Google Colab environment throws the error. I can't really find why the behavior is different here, could be OS-related. Some relevant docs: https://mypy.readthedocs.io/en/stable/runtime_troubles.html

**Comment by JoerivanEngelen** [comment] 2024-02-23 14:25
The iMOD Python 0.15.3 release fixes all kinds of related issues with pip installation. I am now able to import iMOD Python into Google Colab without issues, therefore closing this issue.

**Closed by JoerivanEngelen** 2024-02-23 14:25 UTC
Labels: bug, priority

**Comment by JoerivanEngelen** [comment] 2024-02-23 15:51
I've yanked the 0.15.2 release on PyPI, I think this shouldn't affect the 0.15.2 release on conda-forge, which works.
